export const STICKER_CONFIG = [
  {
    id: "sticker-heart",
    name: "thỏ",
    type: "image",
    src: "/images/stickers/thỏtrắng.png",
    thumbnail: "/images/stickers/thỏtrắng.png",
    price: 25000,
    layerType: "sticker",
  },
  {
    id: "sticker-star",
    name: "tay cầm",
    type: "image",
    src: "/images/stickers/taycầm.png",
    thumbnail: "/images/stickers/taycầm.png",
    price: 25000,
    layerType: "sticker",
  },
  {
    id: "sticker-flower",
    name: "túi",
    type: "image",
    src: "/images/stickers/túi.png",
    thumbnail: "/images/stickers/túi.png",
    price: 25000,
    layerType: "sticker",
  },
  {
    id: "sticker-tui2",
    name: "túi 2",
    type: "image",
    src: "/images/stickers/túi2.png",
    thumbnail: "/images/stickers/túi2.png",
    price: 25000,
    layerType: "sticker",
  },
  {
    id: "sticker-banh2",
    name: "bánh 2",
    type: "image",
    src: "/images/stickers/bánh2.png",
    thumbnail: "/images/stickers/bánh2.png",
    price: 25000,
    layerType: "sticker",
  },
  {
    id: "sticker-banhquy",
    name: "bánh quy",
    type: "image",
    src: "/images/stickers/bánhquy.png",
    thumbnail: "/images/stickers/bánhquy.png",
    price: 25000,
    layerType: "sticker",
  },
  {
    id: "sticker-bongro",
    name: "bóng rổ",
    type: "image",
    src: "/images/stickers/bóngrổ2.png",
    thumbnail: "/images/stickers/bóngrổ2.png",
    price: 25000,
    layerType: "sticker",
  },
  {
    id: "sticker-cho-husky",
    name: "chó Husky",
    type: "image",
    src: "/images/stickers/chóHusky.png",
    thumbnail: "/images/stickers/chóHusky.png",
    price: 25000,
    layerType: "sticker",
  },
  {
    id: "sticker-cho-pug",
    name: "chó Pug",
    type: "image",
    src: "/images/stickers/chóPug.png",
    thumbnail: "/images/stickers/chóPug.png",
    price: 25000,
    layerType: "sticker",
  },
  {
    id: "sticker-cho-nau",
    name: "chó nâu",
    type: "image",
    src: "/images/stickers/chónâu.png",
    thumbnail: "/images/stickers/chónâu.png",
    price: 25000,
    layerType: "sticker",
  },
  {
    id: "sticker-cho-trang",
    name: "chó trắng",
    type: "image",
    src: "/images/stickers/chótrắng.png",
    thumbnail: "/images/stickers/chótrắng.png",
    price: 25000,
    layerType: "sticker",
  },
  {
    id: "sticker-embe1",
    name: "em bé 1",
    type: "image",
    src: "/images/stickers/embé1.png",
    thumbnail: "/images/stickers/embé1.png",
    price: 25000,
    layerType: "sticker",
  },
  {
    id: "sticker-embe2",
    name: "em bé 2",
    type: "image",
    src: "/images/stickers/embé2.png",
    thumbnail: "/images/stickers/embé2.png",
    price: 25000,
    layerType: "sticker",
  },
  {
    id: "sticker-hoa-hong",
    name: "hoa hồng",
    type: "image",
    src: "/images/stickers/hoahồng.png",
    thumbnail: "/images/stickers/hoahồng.png",
    price: 25000,
    layerType: "sticker",
  },
  {
    id: "sticker-hoa-trang",
    name: "hoa trắng",
    type: "image",
    src: "/images/stickers/hoatrắng.png",
    thumbnail: "/images/stickers/hoatrắng.png",
    price: 25000,
    layerType: "sticker",
  },
  {
    id: "sticker-hoa-xanh",
    name: "hoa xanh",
    type: "image",
    src: "/images/stickers/hoaxanh.png",
    thumbnail: "/images/stickers/hoaxanh.png",
    price: 25000,
    layerType: "sticker",
  },
  {
    id: "sticker-mic",
    name: "mic",
    type: "image",
    src: "/images/stickers/mic.png",
    thumbnail: "/images/stickers/mic.png",
    price: 25000,
    layerType: "sticker",
  },
  {
    id: "sticker-meo-nau",
    name: "mèo nâu",
    type: "image",
    src: "/images/stickers/mèonâu.png",
    thumbnail: "/images/stickers/mèonâu.png",
    price: 25000,
    layerType: "sticker",
  },
  {
    id: "sticker-meo-vang",
    name: "mèo vàng",
    type: "image",
    src: "/images/stickers/mèovàng.png",
    thumbnail: "/images/stickers/mèovàng.png",
    price: 25000,
    layerType: "sticker",
  },
  {
    id: "sticker-mutn",
    name: "mũ tốt nghiệp",
    type: "image",
    src: "/images/stickers/mũtốtnghiệp.png",
    thumbnail: "/images/stickers/mũtốtnghiệp.png",
    price: 25000,
    layerType: "sticker",
  },
  {
    id: "sticker-phone",
    name: "điện thoại",
    type: "image",
    src: "/images/stickers/phone.png",
    thumbnail: "/images/stickers/phone.png",
    price: 25000,
    layerType: "sticker",
  },
  {
    id: "sticker-teddy",
    name: "teddy",
    type: "image",
    src: "/images/stickers/teddy.png",
    thumbnail: "/images/stickers/teddy.png",
    price: 25000,
    layerType: "sticker",
  },
];
