export const LEGO_CONFIG = {
  partConfig: {
    totalWidth: 166,
    totalHeight: 260,

    head:   { width: 156, height: 104, zIndex: 11, offsetX: 5,  offsetY: 89  },
    torso:  { width: 166, height: 125, zIndex: 10, offsetX: 0,  offsetY: 73  },
    legs:   { width: 156, height: 114, zIndex: 9,  offsetX: 5,  offsetY: 88  },
    face:   { width: 47,  height: 78,  zIndex: 13, offsetX: 0,  offsetY: -14 },
    hair:   { width: 90, height: 68, zIndex: 14, offsetX: 0,  offsetY: -20  },
    outfit: { width: 166, height: 125, zIndex: 10, offsetX: 0,  offsetY: 83  },
  },

  assemblyConfig: {
    headToTorso:   { overlap: 6.5 },
    torsoToLegs:   { overlap: 10  },
    snapTolerance: 4,
  },

  // Mobile sizes (scale = 1/1.5 ≈ 0.667 — nhỏ hơn desktop 1.5 lần)
  partConfigMobile: {
    totalWidth: 111,
    totalHeight: 173,

    head:   { width: 104, height: 69, zIndex: 11, offsetX: 3,  offsetY: 59  },
    torso:  { width: 111, height: 83, zIndex: 10, offsetX: 0,  offsetY: 49  },
    legs:   { width: 104, height: 76, zIndex: 9,  offsetX: 3,  offsetY: 59  },
    face:   { width: 31,  height: 52, zIndex: 13, offsetX: 0,  offsetY: -9 },
    hair:   { width: 60, height: 45, zIndex: 14, offsetX: 0,  offsetY: -14  },
    outfit: { width: 111, height: 83, zIndex: 10, offsetX: 0,  offsetY: 55  },
  },

  assemblyConfigMobile: {
    headToTorso:   { overlap: 4.3 },
    torsoToLegs:   { overlap: 6.7 },
    snapTolerance: 3,
  },

  baseParts: {
    head: "/images/lego/body/head_base.png",
    torso: "/images/lego/body/torso_base.png",
    legs: "/images/lego/body/legs_base.png",
  },

  outfits: [],

  legoColors: [
    {
      id: "outfit-do",
      type: "lego",
      name: "Áo Đỏ",
      category: "outfit",
      src: "/images/lego/outfits/do.png",
      thumbnail: "/images/lego/outfits/do.png",
      part: "torso",
      price: 0,
      layerType: "outfit",
    },
    {
      id: "outfit-xanh-bien",
      type: "lego",
      name: "Áo Xanh Biển",
      category: "outfit",
      src: "/images/lego/outfits/xanhbien.png",
      thumbnail: "/images/lego/outfits/xanhbien.png",
      part: "torso",
      price: 0,
      layerType: "outfit",
    },
    {
      id: "outfit-xanh-la",
      type: "lego",
      name: "Áo Xanh Lá",
      category: "outfit",
      src: "/images/lego/outfits/xanhla.png",
      thumbnail: "/images/lego/outfits/xanhla.png",
      part: "torso",
      price: 0,
      layerType: "outfit",
    },
    {
      id: "outfit-hong",
      type: "lego",
      name: "Áo Hồng",
      category: "outfit",
      src: "/images/lego/outfits/hong.png",
      thumbnail: "/images/lego/outfits/hong.png",
      part: "torso",
      price: 0,
      layerType: "outfit",
    },
    {
      id: "outfit-tim",
      type: "lego",
      name: "Áo Tím",
      category: "outfit",
      src: "/images/lego/outfits/tim.png",
      thumbnail: "/images/lego/outfits/tim.png",
      part: "torso",
      price: 0,
      layerType: "outfit",
    },
    {
      id: "outfit-trang",
      type: "lego",
      name: "Áo Trắng",
      category: "outfit",
      src: "/images/lego/outfits/trang.png",
      thumbnail: "/images/lego/outfits/trang.png",
      part: "torso",
      price: 0,
      layerType: "outfit",
    },
    {
      id: "outfit-den",
      type: "lego",
      name: "Áo Đen",
      category: "outfit",
      src: "/images/lego/outfits/den.png",
      thumbnail: "/images/lego/outfits/den.png",
      part: "torso",
      price: 0,
      layerType: "outfit",
    },
    {
      id: "outfit-xam",
      type: "lego",
      name: "Áo Xám",
      category: "outfit",
      src: "/images/lego/outfits/xam.png",
      thumbnail: "/images/lego/outfits/xam.png",
      part: "torso",
      price: 0,
      layerType: "outfit",
    },
    {
      id: "outfit-nau",
      type: "lego",
      name: "Áo Nâu",
      category: "outfit",
      src: "/images/lego/outfits/nau.png",
      thumbnail: "/images/lego/outfits/nau.png",
      part: "torso",
      price: 0,
      layerType: "outfit",
    },
    {
      id: "outfit-xanh-navy",
      type: "lego",
      name: "Áo Xanh Navy",
      category: "outfit",
      src: "/images/lego/outfits/xanhnavy.png",
      thumbnail: "/images/lego/outfits/xanhnavy.png",
      part: "torso",
      price: 0,
      layerType: "outfit",
    },
  ],

  legoPantsColors: [
    {
      id: "pant-do",
      type: "lego",
      name: "Quần Đỏ",
      category: "pant",
      src: "/images/lego/pant/do.png",
      thumbnail: "/images/lego/pant/do.png",
      part: "legs",
      price: 0,
      layerType: "pant",
    },
    {
      id: "pant-xanh-bien",
      type: "lego",
      name: "Quần Xanh Biển",
      category: "pant",
      src: "/images/lego/pant/xanhbien.png",
      thumbnail: "/images/lego/pant/xanhbien.png",
      part: "legs",
      price: 0,
      layerType: "pant",
    },
    {
      id: "pant-xanh-la",
      type: "lego",
      name: "Quần Xanh Lá",
      category: "pant",
      src: "/images/lego/pant/xanhla.png",
      thumbnail: "/images/lego/pant/xanhla.png",
      part: "legs",
      price: 0,
      layerType: "pant",
    },
    {
      id: "pant-hong",
      type: "lego",
      name: "Quần Hồng",
      category: "pant",
      src: "/images/lego/pant/hong.png",
      thumbnail: "/images/lego/pant/hong.png",
      part: "legs",
      price: 0,
      layerType: "pant",
    },
    {
      id: "pant-tim",
      type: "lego",
      name: "Quần Tím",
      category: "pant",
      src: "/images/lego/pant/tim.png",
      thumbnail: "/images/lego/pant/tim.png",
      part: "legs",
      price: 0,
      layerType: "pant",
    },
    {
      id: "pant-trang",
      type: "lego",
      name: "Quần Trắng",
      category: "pant",
      src: "/images/lego/pant/trang.png",
      thumbnail: "/images/lego/pant/trang.png",
      part: "legs",
      price: 0,
      layerType: "pant",
    },
    {
      id: "pant-den",
      type: "lego",
      name: "Quần Đen",
      category: "pant",
      src: "/images/lego/pant/den.png",
      thumbnail: "/images/lego/pant/den.png",
      part: "legs",
      price: 0,
      layerType: "pant",
    },
    {
      id: "pant-xam",
      type: "lego",
      name: "Quần Xám",
      category: "pant",
      src: "/images/lego/pant/xam.png",
      thumbnail: "/images/lego/pant/xam.png",
      part: "legs",
      price: 0,
      layerType: "pant",
    },
    {
      id: "pant-nau",
      type: "lego",
      name: "Quần Nâu",
      category: "pant",
      src: "/images/lego/pant/nau.png",
      thumbnail: "/images/lego/pant/nau.png",
      part: "legs",
      price: 0,
      layerType: "pant",
    },
    {
      id: "pant-xanh-navy",
      type: "lego",
      name: "Quần Xanh Navy",
      category: "pant",
      src: "/images/lego/pant/xanhnavy.png",
      thumbnail: "/images/lego/pant/xanhnavy.png",
      part: "legs",
      price: 0,
      layerType: "pant",
    },
  ],

  faces: [
    {
      id: "face-happy",
      type: "lego",
      name: "Mặt Vui",
      category: "face",
      src: "/images/lego/faces/happy.png",
      thumbnail: "/images/lego/faces/happy.png",
      part: "head",
      price: 0,
      layerType: "face",
    },
    {
      id: "face-smile",
      type: "lego",
      name: "Mặt Cười",
      category: "face",
      src: "/images/lego/faces/smile.png",
      thumbnail: "/images/lego/faces/smile.png",
      part: "head",
      price: 0,
      layerType: "face",
    },
    {
      id: "face-neutral",
      type: "lego",
      name: "Mặt Bình thường",
      category: "face",
      src: "/images/lego/faces/neutral.png",
      thumbnail: "/images/lego/faces/neutral.png",
      part: "head",
      price: 0,
      layerType: "face",
    },
    {
      id: "face-wink",
      type: "lego",
      name: "Mặt Nháy mắt",
      category: "face",
      src: "/images/lego/faces/wink.png",
      thumbnail: "/images/lego/faces/wink.png",
      part: "head",
      price: 0,
      layerType: "face",
    },
    {
      id: "face-15",
      type: "lego",
      name: "Mặt 5",
      category: "face",
      src: "/images/lego/faces/15.png",
      thumbnail: "/images/lego/faces/15.png",
      part: "head",
      price: 0,
      layerType: "face",
      widthAdjust: -1.5,
      heightAdjust: -0.5,
      offsetYExtra: -1,
    },
    {
      id: "face-34",
      type: "lego",
      name: "Mặt 6",
      category: "face",
      src: "/images/lego/faces/34.png",
      thumbnail: "/images/lego/faces/34.png",
      part: "head",
      price: 0,
      layerType: "face",
      widthAdjust: -0.5,
      heightAdjust: -0.5,
    },
  ],

  facesFemale: [
    {
      id: "face-female-02",
      type: "lego",
      name: "Mặt nữ 1",
      category: "face",
      src: "/images/lego/faces/faceswoman/02.png",
      thumbnail: "/images/lego/faces/faceswoman/02.png",
      part: "head",
      price: 0,
      layerType: "face",
      offsetYExtra: -1.2,
    },
    {
      id: "face-female-06",
      type: "lego",
      name: "Mặt nữ 2",
      category: "face",
      src: "/images/lego/faces/faceswoman/06.png",
      thumbnail: "/images/lego/faces/faceswoman/06.png",
      part: "head",
      price: 0,
      layerType: "face",
      sizeScale: 0.99,
      offsetYExtra: -0.1,
    },

    {
      id: "face-female-10",
      type: "lego",
      name: "Mặt nữ 3",
      category: "face",
      src: "/images/lego/faces/faceswoman/10.png",
      thumbnail: "/images/lego/faces/faceswoman/10.png",
      part: "head",
      price: 0,
      layerType: "face",
      offsetYExtra: -2.2,
      heightAdjust: -2,
    },
    {
      id: "face-female-16",
      type: "lego",
      name: "Mặt nữ 4",
      category: "face",
      src: "/images/lego/faces/faceswoman/16.png",
      thumbnail: "/images/lego/faces/faceswoman/16.png",
      part: "head",
      price: 0,
      layerType: "face",
      offsetYExtra: 1.8,
    },
    {
      id: "face-female-45",
      type: "lego",
      name: "Mặt nữ 5",
      category: "face",
      src: "/images/lego/faces/faceswoman/45.png",
      thumbnail: "/images/lego/faces/faceswoman/45.png",
      part: "head",
      price: 0,
      layerType: "face",
      heightAdjust: -2,
    },

    {
      id: "face-female-matnu6",
      type: "lego",
      name: "Mặt nữ 6",
      category: "face",
      src: "/images/lego/faces/faceswoman/matnu6.png",
      thumbnail: "/images/lego/faces/faceswoman/matnu6.png",
      part: "head",
      price: 0,
      layerType: "face",
      sizeScale: 0.94158594,
      offsetXExtra: 1,
      offsetYExtra: 2,
    },
  ],

  hairs: [
    {
      id: "hair-nam-1",
      type: "lego",
      name: "Tóc Nam 1",
      category: "hair",
      gender: "nam",
      src: "/images/lego/hair/nam/tocnam1.png",
      thumbnail: "/images/lego/hair/nam/tocnam1.png",
      part: "head",
      price: 0,
      layerType: "hair",
      offsetYExtra: 10,
      sizeScale: 0.8901314775,
      offsetXExtra: 1,
    },
    {
      id: "hair-nam-2",
      type: "lego",
      name: "Tóc Nam 2",
      category: "hair",
      gender: "nam",
      src: "/images/lego/hair/nam/tocnam2.png",
      thumbnail: "/images/lego/hair/nam/tocnam2.png",
      part: "head",
      price: 0,
      layerType: "hair",
      offsetYExtra: 8,
      sizeScale: 0.894466,
      offsetXExtra: 1,
    },

    {
      id: "hair-nam-3",
      type: "lego",
      name: "Tóc Nam 3",
      category: "hair",
      gender: "nam",
      src: "/images/lego/hair/nam/tocnam3.png",
      thumbnail: "/images/lego/hair/nam/tocnam3.png",
      part: "head",
      price: 0,
      layerType: "hair",
      offsetYExtra: 11,
      sizeScale: 0.872913,
      offsetXExtra: -1,
    },
    {
      id: "hair-nam-4",
      type: "lego",
      name: "Tóc Nam 4",
      category: "hair",
      gender: "nam",
      src: "/images/lego/hair/nam/tocnam4.png",
      thumbnail: "/images/lego/hair/nam/tocnam4.png",
      part: "head",
      price: 0,
      layerType: "hair",
      offsetYExtra: 6,
      sizeScale: 0.894466,
      offsetXExtra: -0.5,
    },
    {
      id: "hair-nam-5",
      type: "lego",
      name: "Tóc Nam 5",
      category: "hair",
      gender: "nam",
      src: "/images/lego/hair/nam/tocnam5.png",
      thumbnail: "/images/lego/hair/nam/tocnam5.png",
      part: "head",
      price: 0,
      layerType: "hair",
      offsetYExtra: 9,
      sizeScale: 0.872913,
      offsetXExtra: 1,
    },
    {
      id: "hair-nam-6",
      type: "lego",
      name: "Tóc Nam 6",
      category: "hair",
      gender: "nam",
      src: "/images/lego/hair/nam/tocnam6.png",
      thumbnail: "/images/lego/hair/nam/tocnam6.png",
      part: "head",
      price: 0,
      layerType: "hair",
      offsetYExtra: 10,
      sizeScale: 0.872913,
      offsetXExtra: 1,
    },
    {
      id: "hair-nam-7",
      type: "lego",
      name: "Tóc Nam 7",
      category: "hair",
      gender: "nam",
      src: "/images/lego/hair/nam/tocnam7.png",
      thumbnail: "/images/lego/hair/nam/tocnam7.png",
      part: "head",
      price: 0,
      layerType: "hair",
      offsetYExtra: 8,
      sizeScale: 0.872913,
      offsetXExtra: 1,
    },
    {
      id: "hair-nam-8",
      type: "lego",
      name: "Tóc Nam 8",
      category: "hair",
      gender: "nam",
      src: "/images/lego/hair/nam/tocnam8.png",
      thumbnail: "/images/lego/hair/nam/tocnam8.png",
      part: "head",
      price: 0,
      layerType: "hair",
      sizeScale: 0.754369,
      offsetYExtra: 10,
      offsetXExtra: 1,
    },
    {
      id: "hair-nam-9",
      type: "lego",
      name: "Tóc Nam 9",
      category: "hair",
      gender: "nam",
      src: "/images/lego/hair/nam/tocnam9.png",
      thumbnail: "/images/lego/hair/nam/tocnam9.png",
      part: "head",
      price: 0,
      layerType: "hair",
      sizeScale: 0.754369,
      offsetYExtra: 10.5,
      offsetXExtra: 0,
    },
    {
      id: "hair-nu-1",
      type: "lego",
      name: "Tóc Nữ 1",
      category: "hair",
      gender: "nu",
      src: "/images/lego/hair/nu/tocnu1.png",
      thumbnail: "/images/lego/hair/nu/tocnu1.png",
      part: "head",
      price: 0,
      layerType: "hair",
      sizeScale: 1.64802374253, // giảm thêm 1%
      heightAdjust: 1,
      offsetYExtra: -1,
      offsetXExtra: -2,
    },
    {
      id: "hair-nu-2",
      type: "lego",
      name: "Tóc Nữ 2",
      category: "hair",
      gender: "nu",
      src: "/images/lego/hair/nu/tocnu2.png",
      thumbnail: "/images/lego/hair/nu/tocnu2.png",
      part: "head",
      price: 0,
      layerType: "hair",
      sizeScale: 1.01365,
      heightAdjust: 1,
      offsetYExtra: 14,
      rotation: 2,
    },
    {
      id: "hair-nu-3",
      type: "lego",
      name: "Tóc Nữ 3",
      category: "hair",
      gender: "nu",
      src: "/images/lego/hair/nu/tocnu3.png",
      thumbnail: "/images/lego/hair/nu/tocnu3.png",
      part: "head",
      price: 0,
      layerType: "hair",
      offsetYExtra: 11,
      sizeScale: 1.1737,
    },
    {
      id: "hair-nu-4",
      type: "lego",
      name: "Tóc Nữ 4",
      category: "hair",
      gender: "nu",
      src: "/images/lego/hair/nu/tocnu4.png",
      thumbnail: "/images/lego/hair/nu/tocnu4.png",
      part: "head",
      price: 0,
      layerType: "hair",
      offsetYExtra: 15, // Dịch xuống dưới 3px
      offsetXExtra: -2, // Dịch sang trái 2px
      sizeScale: 0.9603,  // Thu nhỏ 10%
    },
    {
      id: "hair-nu-5",
      type: "lego",
      name: "Tóc Nữ 5",
      category: "hair",
      gender: "nu",
      src: "/images/lego/hair/nu/tocnu5.png",
      thumbnail: "/images/lego/hair/nu/tocnu5.png",
      part: "head",
      price: 0,
      layerType: "hair",
      sizeScale: 1.871494,
      heightAdjust: 1,
      offsetYExtra: 21,
      offsetXExtra: -5.8,
    },
    {
      id: "hair-nu-6",
      type: "lego",
      name: "Tóc Nữ 6",
      category: "hair",
      gender: "nu",
      src: "/images/lego/hair/nu/tocnu6.png",
      thumbnail: "/images/lego/hair/nu/tocnu6.png",
      part: "head",
      price: 0,
      layerType: "hair",
      sizeScale: 1.69078624715,
      heightAdjust: 1,
      offsetYExtra: 23.5,
      offsetXExtra: -5,
      rotation: 2,
    },

    {
      id: "hair-nu-7",
      type: "lego",
      name: "Tóc Nữ 7",
      category: "hair",
      gender: "nu",
      src: "/images/lego/hair/nu/tocnu7.png",
      thumbnail: "/images/lego/hair/nu/tocnu7.png",
      part: "head",
      price: 0,
      layerType: "hair",
      sizeScale: 1.89955440345,
      offsetYExtra: 22,
      offsetXExtra: -5,
    },
  ],
};








